name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Lint and Test API
        working-directory: apps/api
        run: |
          npm run lint
          npm run test
      - name: Lint and Test Web
        working-directory: apps/web
        run: |
          npm run lint
          npm run test
      - name: Build API Docker image
        run: docker build -t rescue-net-api apps/api
      - name: Build Web Docker image
        run: docker build -t rescue-net-web apps/web
